all: pt
	ls

big:
	pdflatex big
	bibtex   big
	pdflatex big
	pdflatex big

small:
	pdflatex small
	bibtex   small
	pdflatex small
	pdflatex small

pt:
	pdflatex pt
	bibtex   pt
	pdflatex pt
	pdflatex pt
